### ISSUE TITLE
Duration

### ISSUE THREAD

**Issue by capriciousduck** [dermasmid/scrapetube#1]
Is it possible to get the video duration?

**Comment by dermasmid** [comment]
Sure, `video['thumbnailOverlays'][0]['thumbnailOverlayTimeStatusRenderer']['text']['simpleText']` contains the video duration.

**Comment by capriciousduck** [comment]
Oh. That great. It's great. How do I convert the output into seconds?

**Comment by dermasmid** [comment]
This might help:
```python
import scrapetube
import datetime
videos = scrapetube.get_channel("UC9-y-6csu5WGm29I7JiwpnA", sort_by='popular')
for video in videos:
    duration = video['thumbnailOverlays'][0]['thumbnailOverlayTimeStatusRenderer']['text']['simpleText']
    seconds = str((datetime.datetime.strptime(duration, '%M:%S') - datetime.datetime(1900, 1, 1)).total_seconds()).split('.')[0]
    print(seconds)
```
Please keep in mind that this will only work for a duration that does not have any hours like this 08:16, but for a duration with hours, you will have to replace `'%M:%S'` with `'%H%M:%S'`.
Hope it helps.

**Comment by capriciousduck** [comment]
Yes, it worked. Thanks.

**Comment by capriciousduck** [comment]
And I've got some personal question. However long have you been learning python before creating scrapetube? I just want to know to help me set some real expectations with my learning.

**Comment by dermasmid** [comment]
Feel free to reach out by email, i'll be heppy to help.

**Comment by capriciousduck** [comment]
Oh. Thanks. Okay.
