### ISSUE TITLE
Set Accept-Language header to English

### ISSUE THREAD

**Issue by Theta-Dev** [dermasmid/scrapetube#10]
Some of the data returned by the internal YouTube API is localized, e.g. the upload date string. If no Accept-Language header is present, YouTube will assume the language via the users's IP.

This leads to inconsistent output data and possible parsing errors if scrapetube is used in a non-English-speaking country.

That's why I would suggest setting the Accept-Language header to `en`. I am from Germany and can confirm that YouTube ouputs English date strings with that setting.

```py
session = requests.Session()
session.headers[
    "User-Agent"
] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101
Safari/537.36"
session.headers["Accept-Language"] = "en"
```

**Comment by VladislavSmolyanoy** [comment]
Weird. When I edit the scrapetube.py file, nothing changes. What are the steps that you took in order to change the file?

**Comment by dermasmid** [comment]
fixed
