### ISSUE TITLE
"ResourceWarning: Unclosed socket" while stopping generator iteration

### ISSUE THREAD

**Issue by isaacclinton** [dermasmid/scrapetube#2]
I would like to exit the get channel generator after I have reached the video I want. However, it seems there is no safe exit, a socket is left open. Below is the code:
```python
import scrapetube

channel_videos_generator = scrapetube.get_channel(channel_id=channel_id, sort_by="newest")

for video in channel_videos_generator:
    if video["videoId"] != since_video_id:
        yield video["videoId"]
    else:
        channel_videos_generator.close()
```
When I run the above code, I get the warning below:
```none
ResourceWarning: unclosed <ssl.SSLSocket fd=756, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.20', 58222), raddr=('216.58.223.78', 443)>
  channel_videos_generator.close()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by dermasmid** [comment]
thanks for reporting!
i had to add this to reproduce, i guess you were running it with some sort of testing
```python
import warnings

warnings.filterwarnings(action="always", message="unclosed", category=ResourceWarning)
```

**Comment by isaacclinton** [comment]
It's true, I have incorporated testing in my codebase. I filtered the warning. I went through scrapetube's source code and it seems a session in a while loop might not be closed after exiting abruptly; or maybe the warning is only raised during testing. Thanks though, in case the problem is inherent, and you consider fixing it, I will appreciate.
