### ISSUE TITLE
PIP package doesn't include the "content_type" Filter

### ISSUE THREAD

**Issue by SpeedOf-Shadow** [dermasmid/scrapetube#26]
Hey, 

Firstly, amazing job on the code, saved a ton of time for me.

I have noticed that the pip package doesn't include the content_type filter in the source code. I thought I will point that out.

Cheers

**Comment by ItsJoeTurner** [comment]
+1, the content_type='videos' is not working.

> get_channel() got an unexpected keyword argument 'content_type'

**Comment by amlsmm** [comment]
This feature was implemented in the last commit and is functional in the raw code, but the maintainers should update the pip package

**Comment by dermasmid** [comment]
released `2.3.2`
