### ISSUE TITLE
No attribute 'channel_url'

### ISSUE THREAD

**Issue by Melonadev** [dermasmid/scrapetube#3]
Scrapetube's documentation says this about the parameter 'channel_url':

**channel_url** (`str`, optional) – The url to the channel you want to get the videos for. Since there is a few type’s of channel url’s, you can use the one you want by passing it here instead of using `channel_id`.

![image](https://user-images.githubusercontent.com/66422959/134455094-1d158b5d-8248-4380-883d-87b0f16e7b21.png)

...yet I can't actually use that parameter:

```
>>> videos = scrapetube.channel_url("https://www.youtube.com/c/Cmaj7/videos")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scrapetube' has no attribute 'channel_url'
```

**Comment by dermasmid** [comment]
channel_url is an argument that you pass to the `get_channel` function.
so what you want to do is:
```python
import scrapetube
videos = scrapetube.get_channel(channel_url="https://www.youtube.com/c/Cmaj7")
for video in videos:
    print(video)
```
note that i removed the `/videos` from the url, as you are supposed to pass a link to the channel home page.

**Comment by Melonadev** [comment]
Thanks, it works now!

Notes to self:

If I want to print **only the video IDs**, the indented block at the end should be this instead:
`    print(video['videoId'])`

If I want to print only the video URLs (the complete links), the indented block at the end should be this instead:
`    print('https://www.youtube.com/watch?v=' + video['videoId'])`
