### ISSUE TITLE
Unable to get popular YouTube channel videos after 2.4.0

### ISSUE THREAD

**Issue by asif21089** [dermasmid/scrapetube#31]
Hi, I am facing issues after latest update of the package.

In scrapetube.get_channel("UCCezIgC97PvUuR4_gbFUs5g", sort_by="popular"); the function is not retrieving popular videos instead getting the recent videos only. 

Please fix it.

**Comment by dermasmid** [comment]
it seems like the api has been changed, ill try to find out how sorting is passed nowadays

**Comment by asif21089** [comment]
Thanks hoping to get a solution soon.

**Comment by dermasmid** [comment]
fixed
