### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by rootinthemood** [dermasmid/scrapetube#36]
```
import scrapetube

videos = scrapetube.get_channel("UCCezIgC97PvUuR4_gbFUs5g")

for video in videos:
    print(video['videoId'])
```

results in:

```
Traceback (most recent call last):
  File "/tmp/test/main.py", line 5, in <module>
    for video in videos:
  File "/tmp/test/scrapetube.py", line 75, in get_channel
    for video in videos:
  File "/tmp/test/scrapetube.py", line 199, in get_videos
    client = json.loads(
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Saharsh1223** [comment]
same for me :(

**Comment by Nutzer123** [comment]
same here. Looks like the function: get_initial_data() do not return the needed content.

**Comment by dermasmid** [comment]
im unable to reproduce for now, i tried connecting through a vpn, still did not get this

**Comment by rootinthemood** [comment]
> im unable to reproduce for now, i tried connecting through a vpn, still did not get this

That got me thinking. Without vpn in my country I get the error, with vpn in my country I get error. With vpn in Germany I get error. But vpn in United States I get no error and it works.

**Comment by dermasmid** [comment]
yeah, i see it now when connected to Germany, ill have a look later

**Comment by rootinthemood** [comment]
Tested with vpn in these countries:
```
Austria:        error
Belgium:        error
Brazil:         working
Bulgaria:       error
Canada:         working
Czechia:        error
Alruba:         error
Germany:        error
Ireland:        error
Japan:          working
Latvia:         working
Netherlands:    error
New-Zealand:    working
Norway:         error
Romania:        error
Serbia:         working
Singapore:      working
Spain:          error
Sweden:         error
Switzerland:    error
Ukraine:        working
Great Britain:  error
United States:  working
```

**Comment by twissell-** [comment]
Hi everyone, 

Seems to be related to cookies. The html returned by [this line](https://github.com/dermasmid/scrapetube/blob/0b3090652d1026c0c72fff3078f198ec5e65ea9a/scrapetube/scrapetube.py#L198) renders the following:

![image](https://github.com/dermasmid/scrapetube/assets/4590748/b19d6e75-1da8-4802-a3cb-c8e56964923f)

**Comment by Nutzer123** [comment]
hey,
looks like a dirty solution but i added the following line inside the get_channel() function 
`url = url+"?cbrd=1&ucbcb=1"`

at the moment for me its not clear what the s
![bypass_consent_page](https://github.com/dermasmid/scrapetube/assets/28789408/52d7058a-018d-4697-89a3-5d2319d7028d)
hortcuts means but you can bypass the consent page ;)

**Comment by mgesteiro** [comment]
@Nutzer123  patchs works for me 👌
