### ISSUE TITLE
strangely, get_video funtcion doesn't work 

### ISSUE THREAD

**Issue by usernamecannotbeempty** [dermasmid/scrapetube#49]
Use replit free environment.

I kept getting the error message using the **scrapetube.get_video** function.
I don't understand why because the code looks fine.

It works after I create a custom python file that only keeps the functions I need for get_video.

``
import json
from typing import Generator

import requests
from typing_extensions import Literal

type_property_map = {
    "videos": "videoRenderer",
    "streams": "videoRenderer",
    "shorts": "reelItemRenderer"
}

def get_session() -> requests.Session:
  session = requests.Session()
  session.headers[
      "User-Agent"
  ] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
  session.headers["Accept-Language"] = "en"
  return session

def get_initial_data(session: requests.Session, url: str) -> str:
  session.cookies.set("CONSENT", "YES+cb", domain=".youtube.com")
  response = session.get(url, params={"ucbcb":1})

  html = response.text
  return html

def get_json_from_html(html: str, key: str, num_chars: int = 2, stop: str = '"') -> str:
  pos_begin = html.find(key) + len(key) + num_chars
  pos_end = html.find(stop, pos_begin)
  return html[pos_begin:pos_end]

def search_dict(partial: dict, search_key: str) -> Generator[dict, None, None]:
  stack = [partial]
  while stack:
      current_item = stack.pop(0)
      if isinstance(current_item, dict):
          for key, value in current_item.items():
              if key == search_key:
                  yield value
              else:
                  stack.append(value)
      elif isinstance(current_item, list):
          for value in current_item:
              stack.append(value)

def get_video(
  id: str,
) -> dict:

  """Get a single video.

  Parameters:
      id (``str``):
          The video id from the video you want to get.
  """

  session = get_session()
  url = f"https://www.youtube.com/watch?v={id}"
  html = get_initial_data(session, url)
  client = json.loads(
      get_json_from_html(html, "INNERTUBE_CONTEXT", 2, '"}},') + '"}}'
  )["client"]
  session.headers["X-YouTube-Client-Name"] = "1"
  session.headers["X-YouTube-Client-Version"] = client["clientVersion"]
  data = json.loads(
      get_json_from_html(html, "var ytInitialData = ", 0, "};") + "}"
  )
  return next(search_dict(data, "videoPrimaryInfoRenderer"))
``

**Comment by SurajBhari** [comment]
he forgot to import it in [__init__](https://github.com/dermasmid/scrapetube/blob/master/scrapetube/__init__.py)
