### ISSUE TITLE
[Question] How to search for the next page when I want?

### ISSUE THREAD

**Issue by HubKing** [dermasmid/scrapetube#50]
I have tried the following code, but it kept on searching on its own. I am not good at Python, so I am not sure how that is possible, but my guess is that `get_search` is asynchronously keep searching, and Python's `for` statement keeps monitoring `videos` for newly added elements and continues looping?

```
import scrapetube

videos = scrapetube.get_search("what to search",  sort_by="upload_date")

for video in videos:
    print(video["title"]["runs"][0]["text"])
```

But what I want is manually continuing the search when I want, in the traditional way, like having "more" button and when the user presses it, it shows more search results. Is that possible with this library?

**Comment by SurajBhari** [comment]
you mean this way ? 
```

import scrapetube

videos = scrapetube.get_search("what to search",  sort_by="upload_date")

count = 0
for video in videos:
    count += 1
    print(video["title"]["runs"][0]["text"])
    if count % 20 == 0:
        if input("Continue? (y/n): ").lower() == "n":
            break
        ```

**Comment by HubKing** [comment]
Does it get 20 items

**Comment by SurajBhari** [comment]
in each iteration. yes
