### ISSUE TITLE
get_search  weird output length

### ISSUE THREAD

**Issue by MatFrancois** [dermasmid/scrapetube#56]
Hello
Am I doing something wrong? It seems like get_search always finds around 500-600 results even if there are more (see screenshot below), and there is not the same amount of videos from one time to the next (600 for global warming vs 2 million in reality?).
Do you know why ?

```python
In [1]: import scrapetube
In [2]: videos = scrapetube.get_search("global warming")
In [3]: len([1 for _ in videos])
Out[3]: 604

In [4]: videos = scrapetube.get_search("global warming")
In [5]: len([1 for _ in videos])
Out[5]: 605

In [6]: videos = scrapetube.get_search("global warming")
In [7]: len([1 for _ in videos])
Out[7]: 602

```

![image](https://github.com/dermasmid/scrapetube/assets/36268801/f90c2f15-f642-4529-9a7c-072eb2a92bb1)

**Comment by azerum** [comment]
I wrote a JS script that scrolls through the YouTube page until it finds N videos. I ran it with N=1000, and query="global warming". Interestingly, YouTube shown "No more results" message after 688 videos (on the attached picture, you can see the output of querying CSS selector for video rows elements; keep in mind that some rows can be shorts or live streams; it yielded only 688 elements)

So perhaps the YouTube application itself it not designed to yield more than that many videos?

<img width="1280" alt="global-warming" src="https://github.com/dermasmid/scrapetube/assets/60925680/89cf3a17-d6a2-471b-a974-6d119681b9cb">

**Comment by MatFrancois** [comment]
Thanks for your reply.
> So perhaps the YouTube application itself it not designed to yield more than that many videos?

You're right, I tried through the Youtube API and it has the same behaviour. If you want more than 600 results, you have to order by date, take the oldest video and make a new request from this date.

**Comment by azerum** [comment]
Thanks for sharing

`get_search()` allows to sort by oldest or newest videos, but looks like it doesn't have a way to pass the date to start from (unless I am missing something). Did you implement it yourself? Could you tell which API request params you have used?

**Comment by MatFrancois** [comment]
The problem with this is that you're limited with youtube quota : 100 video search requests /day
For now, I just wrote a small script to get 600 firsts output with the nextpagetoken. You can go further with the date and do something like this: 
```
curl 'https://www.googleapis.com/youtube/v3/search?part=snippet&key=xxx&q=query&maxResults=50&order=date&type=video&publishedAfter=1714730311'
```
You have documentation here: https://developers.google.com/youtube/v3/docs/videos/list?hl=fr

**Comment by azerum** [comment]
Aha, so this approach uses the public API. I though that you've found a way to do that using the private (undocumented) API, hence avoiding the quota. Thanks for the details

**Comment by azerum** [comment]
@MatFrancois I've also found a trick that does not require the public API and can be done using scrapetube. It yielded ~6000 unique results with my query

YouTube has search operators that allow to filter by date: `before:YYYY-MM-DD` returns videos before the date (exclusive), `after:YYYY-MM-DD` returns videos after the date (inclusive)

You could take your original `query`, and keep sending queries grouped by year (this is what I've used; one can also try to group by month, week, etc) until there are no more results:

`${query} after:2024-01-01`
`${query} after:2023-01-01 before:2024-01-01`
`${query} after:2022-01-01 before:2023-01-01`
...

Then you can keep unique results by using video ID

**Comment by MatFrancois** [comment]
Very interesting, there are secret query parameters.
It's now easy to iterate over date when we order by date without public API. 

I also noticed that, when your request is ordered by relevance, the results are much bigger (close to the number output of "site:youtube.com query" on google search) than by date.  Furthermore, almost all videos returned when you order by date are given in the very first results of the relevance output.
