### ISSUE TITLE
How I got it working

### ISSUE THREAD

**Issue by qkum** [dermasmid/scrapetube#6]
Partly working for me.

Pip install version did not work. Can't remember the error. (Python 3.8)

Ended up downloading the respiratory as a zip file and unzipped it into my desired folder.

I now use the lovely code by using a modified version of the test script in the 'tests' folder.

That works lovely.

Thanks for sharing 💯

**Comment by dermasmid** [comment]
Thanks for opening this issue, can you please retry installing the package with pip and sharing the output?
