### ISSUE TITLE
Add get_user

### ISSUE THREAD

**Issue by asiergda** [dermasmid/scrapetube#8]
Hi dermasmid,
first thanks for your work, I really appreciate it.
I'm testing scrapetube and I think that if you add a support for youtube user, get_user, in a similar way that get_channel it would expand the use. I modified it in order to test.

Again thanks.

**Comment by dermasmid** [comment]
Hey @asiergda 
Do you want to open a pull request with your changes please?

**Comment by asiergda** [comment]
Hi dermasmid,
the changes are not worthy of pull request...I just added a copy of the get_channel function that you developed with a minimal change. 
Here go the details:
Modified file: scrapetube.py -> a new function called "get_user" copied from get_channel with one difference in url (change channel by user): url=channel_url or f"https://www.youtube.com/**user**/{channel_id}", 

Added code:
...
def get_user(
    channel_id: str = None,
    channel_url: str = None,
    limit: int = None,
    sleep: int = 1,
    sort_by: Literal["newest", "oldest", "popular"] = "newest",
) -> Generator[dict, None, None]:

    """Get videos for a channel.
    Parameters:
        channel_id (``str``, *optional*):
            The channel id from the channel you want to get the videos for.
            If you prefer to use the channel url instead, see ``channel_url`` below.
        channel_url (``str``, *optional*):
            The url to the channel you want to get the videos for.
            Since there is a few type's of channel url's, you can use the one you want
            by passing it here instead of using ``channel_id``.
        limit (``int``, *optional*):
            Limit the number of videos you want to get.
        sleep (``int``, *optional*):
            Seconds to sleep between API calls to youtube, in order to prevent getting blocked.
            Defaults to 1.
        sort_by (``str``, *optional*):
            In what order to retrieve to videos. Pass one of the following values.
            ``"newest"``: Get the new videos first.
            ``"oldest"``: Get the old videos first.
            ``"popular"``: Get the popular videos first. Defaults to "newest".
    """

    sort_by_map = {"newest": "dd", "oldest": "da", "popular": "p"}
    url = "{url}/videos?view=0&sort={sort_by}&flow=grid".format(
        url=channel_url or f"https://www.youtube.com/user/{channel_id}",
        sort_by=sort_by_map[sort_by],
    )
    api_endpoint = "https://www.youtube.com/youtubei/v1/browse"
    videos = get_videos(url, api_endpoint, "gridVideoRenderer", limit, sleep)
    for video in videos:
        yield video
...

A simple test:
➜  ~ python
Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.insert(0, '/path/scrapetube/')
>>> from scrapetube import get_user
>>> from scrapetube import get_channel
>>> 
>>> videos = get_user("the name of the youtube user")
>>> 
>>> video_url_list = []
>>> 
>>> for video in videos:
...     video_url_list.append(video['videoId'])
... 
>>> print(len(video_url_list))
274

I'm testing your code in order to download urls and then create a block list used by squid (Squid-in-the-middle SSL Bump). 
The results are very good.
Thanks for your work and for share it.
Regards

**Comment by dermasmid** [comment]
Hey, there is support for getting the user, by using the `channel_url` parameter and passing the full url to the users page.
Hope this helps, thanks.

**Comment by asiergda** [comment]
Sorry for the delay...Thank you Dermasmid!!!
